---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8082
    description: Generated server url
tags:
  - name: Financial Data API
    description: 기업 재무 정보를 제공하는 API
  - name: Chat Room API
    description: 채팅방 생성, 조회 및 삭제 API
  - name: Stock Data API
    description: 주식 데이터를 제공하는 API
  - name: User API
    description: 회원 가입, 로그인, 카카오 로그인 관련 API
paths:
  "/api/kakao/callback":
    get:
      tags:
        - User API
      summary: 카카오 인증 콜백
      description: 카카오 인증 후 리다이렉트된 요청을 처리합니다.
      operationId: kakaoCallback
      parameters:
        - name: code
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 카카오 로그인 성공 및 세션 저장
          content:
            "*/*":
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: 카카오 로그인 실패
          content:
            "*/*":
              schema:
                type: object
                additionalProperties:
                  type: string
    post:
      tags:
        - User API
      summary: 카카오 인증 콜백
      description: 카카오 인증 후 리다이렉트된 요청을 처리합니다.
      operationId: kakaoCallback_1
      parameters:
        - name: code
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 카카오 로그인 성공 및 세션 저장
          content:
            "*/*":
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: 카카오 로그인 실패
          content:
            "*/*":
              schema:
                type: object
                additionalProperties:
                  type: string
  "/api/update-password":
    post:
      tags:
        - User API
      summary: 비밀번호 업데이트
      description: 이메일을 이용해 비밀번호를 업데이트합니다.
      operationId: updatePassword
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PasswordUpdateRequest"
        required: true
      responses:
        '200':
          description: 비밀번호 업데이트 성공
          content:
            "*/*":
              schema:
                type: string
        '404':
          description: 해당 이메일의 유저를 찾을 수 없음
          content:
            "*/*":
              schema:
                type: string
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: string
  "/api/signup":
    post:
      tags:
        - User API
      summary: 회원가입
      description: 유저 정보를 받아 새로운 유저를 생성합니다.
      operationId: join
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Joindto"
        required: true
      responses:
        '200':
          description: 회원가입 성공
          content:
            "*/*":
              schema:
                type: string
        '400':
          description: 회원가입 실패
          content:
            "*/*":
              schema:
                type: string
  "/api/login":
    post:
      tags:
        - User API
      summary: 로그인
      description: 이메일과 비밀번호를 이용해 로그인합니다.
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 로그인 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 이메일 또는 비밀번호
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 내부 서버 오류
          content:
            "*/*":
              schema:
                type: object
  "/api/kakao/session":
    post:
      tags:
        - User API
      summary: 카카오 로그인 세션 생성
      description: 카카오 로그인 후 세션을 생성합니다.
      operationId: createKakaoSession
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 세션 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 유저 정보를 찾을 수 없음
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
  "/api/stock-data":
    get:
      tags:
        - Stock Data API
      summary: 회사 이름 및 날짜 범위로 주식 데이터를 조회합니다.
      operationId: getStockData
      parameters:
        - name: companyName
          in: query
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
        - name: endDate
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 데이터 조회 성공
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/AggregatedDataset"
        '400':
          description: 잘못된 날짜 형식
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/AggregatedDataset"
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/AggregatedDataset"
  "/api/session":
    get:
      tags:
        - User API
      summary: 세션 조회
      description: 현재 로그인된 유저의 세션 정보를 반환합니다.
      operationId: getSession
      responses:
        '200':
          description: 세션 정보 반환 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 활성화된 세션이 없습니다.
          content:
            "*/*":
              schema:
                type: object
  "/api/rooms":
    get:
      tags:
        - Chat Room API
      summary: 사용자의 채팅방 목록을 조회합니다.
      operationId: getUserChatRooms
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 채팅방 목록 조회 성공
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ChatRoom"
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ChatRoom"
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ChatRoom"
  "/api/logout":
    get:
      tags:
        - User API
      summary: 로그아웃
      description: 현재 세션을 무효화하고 로그아웃 처리합니다.
      operationId: logout
      responses:
        '200':
          description: 로그아웃 성공
          content:
            "*/*":
              schema:
                type: object
  "/api/financials":
    get:
      tags:
        - Financial Data API
      summary: 기업 재무 정보를 조회합니다.
      operationId: getFinancials
      parameters:
        - name: corp_code
          in: query
          required: true
          schema:
            type: string
        - name: bsns_year
          in: query
          required: true
          schema:
            type: string
        - name: reprt_code
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 재무 정보 조회 성공
          content:
            "*/*":
              schema:
                type: string
        '400':
          description: 잘못된 요청 파라미터
          content:
            "*/*":
              schema:
                type: string
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: string
  "/api/room/delete":
    delete:
      tags:
        - Chat Room API
      summary: 채팅방을 삭제합니다.
      operationId: deleteChatRoom
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: object
        required: true
      responses:
        '200':
          description: 채팅방 삭제 성공
          content:
            "*/*":
              schema:
                type: object
        '404':
          description: 채팅방을 찾을 수 없음 또는 권한 없음
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
  "/api/room":
    get:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom
      parameters:
        - name: payload
          in: query
          required: true
          schema:
            type: object
            additionalProperties:
              type: string
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
    put:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom_3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
    post:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom_2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
    delete:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom_5
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
    options:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom_6
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
    head:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom_1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
    patch:
      tags:
        - Chat Room API
      summary: 새로운 채팅방을 생성합니다.
      operationId: createChatRoom_4
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        '200':
          description: 채팅방 생성 성공
          content:
            "*/*":
              schema:
                type: object
        '400':
          description: 잘못된 요청
          content:
            "*/*":
              schema:
                type: object
        '500':
          description: 서버 오류 발생
          content:
            "*/*":
              schema:
                type: object
components:
  schemas:
    PasswordUpdateRequest:
      type: object
      properties:
        email:
          type: string
        newPassword:
          type: string
    Joindto:
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
        name:
          type: string
        birthdate:
          type: string
          format: date
        investmentType:
          type: string
    AggregatedDataset:
      type: object
      properties:
        asset_id:
          type: integer
          format: int32
        asset_name:
          type: string
        trade_date:
          type: string
          format: date-time
        close:
          type: number
        open:
          type: number
        high:
          type: number
        low:
          type: number
        volume:
          type: integer
          format: int64
        exchange:
          type: string
        asset_type:
          type: string
        national:
          type: string
    ChatRoom:
      type: object
      properties:
        chatroomId:
          type: integer
          format: int32
        userId:
          type: string
        openedAt:
          type: string
          format: date-time
        roomName:
          type: string
